"""
AI Chatbot Integration Test Script
===================================
This script tests the complete integration from Python to the AI model.
Run this to verify that the chatbot is using the REAL AI model.
"""

import sys
import os

# Add the ai/chatbot directory to Python path
chatbot_ai_path = os.path.abspath(os.path.join(os.path.dirname(__file__), 'ai', 'chatbot'))
sys.path.insert(0, chatbot_ai_path)

print("=" * 60)
print("AI Chatbot Integration Test")
print("=" * 60)

# Test 1: Import AI modules
print("\n[Test 1] Importing AI modules...")
try:
    from workflow import Workflow
    from models import State
    from agents import rewrite_query_agent, streaming_response_agent
    print("✅ Successfully imported: Workflow, State, agents")
except Exception as e:
    print(f"❌ Failed to import AI modules: {e}")
    print("\nPlease ensure:")
    print("1. ai/chatbot directory exists")
    print("2. All required files are present (workflow.py, models.py, agents.py)")
    sys.exit(1)

# Test 2: Check if .env file exists
print("\n[Test 2] Checking for .env configuration...")
env_paths = [
    os.path.join('ai', 'chatbot', '.env'),
    os.path.join('backend', 'ai_services', 'chatbot', '.env')
]
env_found = False
for env_path in env_paths:
    if os.path.exists(env_path):
        print(f"✅ Found .env file at: {env_path}")
        env_found = True

        # Check if OPENAI_API_KEY is set
        with open(env_path, 'r') as f:
            content = f.read()
            if 'OPENAI_API_KEY' in content and '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' not in content:
                print("✅ OPENAI_API_KEY appears to be configured")
            else:
                print("⚠️  OPENAI_API_KEY not configured properly")
                print("   Please add your OpenAI API key to the .env file")

if not env_found:
    print("⚠️  No .env file found. Please create one with your OPENAI_API_KEY")
    print("\nExample:")
    print("  OPENAI_API_KEY=OPENAI_API_KEY_PLACEHOLDER")

# Test 3: Initialize workflow
print("\n[Test 3] Initializing AI workflow...")
try:
    workflow = Workflow()
    print("✅ Workflow initialized successfully")
except Exception as e:
    print(f"❌ Failed to initialize workflow: {e}")
    sys.exit(1)

# Test 4: Test model inference (if API key is configured)
print("\n[Test 4] Testing AI model inference...")
print("This will make a real API call to OpenAI (if API key is configured)")

test_state = {
    "messages": [],
    "query": "What are the main symptoms of stroke?",
    "rewritten_query": None,
    "response": None,
}

try:
    import asyncio

    async def test_inference():
        print("\nSending test query: 'What are the main symptoms of stroke?'")
        print("\nAI Response (streaming):")
        print("-" * 60)

        full_response = ""
        async for chunk in workflow.run_streaming(test_state):
            if chunk:
                print(chunk, end='', flush=True)
                full_response += chunk

        print("\n" + "-" * 60)
        return full_response

    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    response = loop.run_until_complete(test_inference())
    loop.close()

    if response and len(response) > 10:
        print("\n✅ AI model inference successful!")
        print(f"   Response length: {len(response)} characters")
        print("\n✅ VERIFICATION: Response is dynamically generated by the AI model")
        print("   (Not a hardcoded response)")
    else:
        print("\n⚠️  AI returned empty or very short response")

except Exception as e:
    print(f"\n❌ Model inference failed: {e}")
    print("\nCommon issues:")
    print("1. OPENAI_API_KEY not set or invalid")
    print("2. No internet connection")
    print("3. Missing dependencies (langchain-openai, langgraph)")
    print("\nTo install dependencies:")
    print("  pip install langchain-openai langchain-core langgraph python-dotenv")

# Final summary
print("\n" + "=" * 60)
print("Test Summary")
print("=" * 60)
print("""
To verify the integration is working:

1. ✅ AI modules import successfully
2. ✅ Workflow initializes without errors
3. ✅ Model generates responses (if API key configured)

Next steps:
1. Start the chatbot service: python backend/ai_services/chatbot/app.py
2. Test via HTTP: curl -X POST http://localhost:5001/chat \\
                    -H "Content-Type: application/json" \\
                    -d '{"message": "test", "history": []}'

For full integration testing, start all services:
- Terminal 1: python backend/ai_services/chatbot/app.py
- Terminal 2: python backend/gateway.py
- Terminal 3: python backend/flask_server/app.py
- Test from Flutter app
""")
print("=" * 60)
